import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface MigrainEpisode {
  id: number;
  date: string;
  time: string;
  severity: string;
  duration: string;
  triggers: string[];
  location: string;
  medication: string;
  weatherConditions: {
    temp: number;
    humidity: number;
    pressure: number;
  };
}

export const generateMigrainePDF = (episodes: MigrainEpisode[], days: number = 30) => {
  const doc = new jsPDF();
  
  // Add header
  doc.setFontSize(20);
  doc.setTextColor(56, 178, 172); // Primary color
  doc.text('Velar - Migraine History Report', 20, 20);
  
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 30);
  doc.text(`Report Period: Last ${days} days`, 20, 37);
  
  // Add statistics summary
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Summary Statistics', 20, 50);
  
  const totalEpisodes = episodes.length;
  const avgDuration = episodes.reduce((acc, ep) => acc + parseFloat(ep.duration.split(' ')[0]), 0) / totalEpisodes;
  const weatherRelated = episodes.filter(ep => 
    ep.triggers.some(t => t.toLowerCase().includes('weather'))
  ).length;
  const weatherPercentage = Math.round((weatherRelated / totalEpisodes) * 100);
  
  doc.setFontSize(11);
  doc.text(`Total Episodes: ${totalEpisodes}`, 25, 60);
  doc.text(`Average Duration: ${avgDuration.toFixed(1)} hours`, 25, 67);
  doc.text(`Weather Related: ${weatherPercentage}%`, 25, 74);
  
  // Prepare table data
  const tableData = episodes.map((episode, index) => [
    (index + 1).toString(),
    episode.date,
    episode.time,
    episode.severity,
    episode.duration,
    episode.triggers.join(', '),
    episode.location,
    episode.medication,
    `${episode.weatherConditions.temp}°C`,
    `${episode.weatherConditions.humidity}%`,
    `${episode.weatherConditions.pressure} hPa`
  ]);

  // Add table
  autoTable(doc, {
    head: [['#', 'Date', 'Time', 'Severity', 'Duration', 'Triggers', 'Location', 'Medication', 'Temp', 'Humidity', 'Pressure']],
    body: tableData,
    startY: 85,
    styles: {
      fontSize: 8,
      cellPadding: 2,
    },
    headStyles: {
      fillColor: [56, 178, 172],
      textColor: [255, 255, 255],
      fontSize: 9,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 20 },
      2: { cellWidth: 15 },
      3: { cellWidth: 18 },
      4: { cellWidth: 15 },
      5: { cellWidth: 30 },
      6: { cellWidth: 18 },
      7: { cellWidth: 20 },
      8: { cellWidth: 15 },
      9: { cellWidth: 15 },
      10: { cellWidth: 15 },
    },
  });
  
  // Add footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 30, doc.internal.pageSize.height - 10);
    doc.text('Generated by Velar - Advanced Migraine Prediction', 20, doc.internal.pageSize.height - 10);
  }
  
  // Save the PDF
  const fileName = `velar-migraine-report-${days}days-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
};

// Generate personalized mock data for each user
export const generatePersonalizedData = (userId?: string) => {
  // Use userId to seed random data for consistency per user
  const seed = userId ? userId.split('').reduce((a, b) => a + b.charCodeAt(0), 0) : Math.random() * 1000;
  
  const episodes: MigrainEpisode[] = [];
  const today = new Date();
  
  // Generate 30-60 days of data
  const daysBack = Math.floor(30 + (seed % 31)); // 30-60 days
  
  for (let i = 0; i < daysBack; i++) {
    // Not every day has an episode
    if ((seed + i) % 4 === 0) { // About 25% chance of episode per day
      const episodeDate = new Date(today);
      episodeDate.setDate(today.getDate() - i);
      
      const severities = ['Mild', 'Moderate', 'Severe'];
      const locations = ['Temporal', 'Frontal', 'Occipital', 'Parietal'];
      const medications = ['Sumatriptan', 'Rizatriptan', 'Ibuprofen', 'Acetaminophen', 'None'];
      const triggerOptions = [
        ['Weather change', 'Pressure drop'],
        ['Stress', 'Work pressure'],
        ['Sleep deprivation', 'Insomnia'],
        ['Bright lights', 'Screen time'],
        ['Food triggers', 'Alcohol'],
        ['Hormonal changes'],
        ['Dehydration'],
        ['Weather change', 'Humidity increase']
      ];
      
      const episodeId = episodes.length + 1;
      const hour = Math.floor(6 + ((seed + i) % 16)); // 6 AM to 10 PM
      const minute = Math.floor((seed + i) % 4) * 15; // 0, 15, 30, 45
      
      episodes.push({
        id: episodeId,
        date: episodeDate.toISOString().split('T')[0],
        time: `${hour.toString().padStart(2, '0')}:${minute.toString().padStart(2, '0')}`,
        severity: severities[(seed + i) % severities.length],
        duration: `${Math.floor(2 + ((seed + i) % 6))} hours`, // 2-7 hours
        triggers: triggerOptions[(seed + i) % triggerOptions.length],
        location: locations[(seed + i) % locations.length],
        medication: medications[(seed + i) % medications.length],
        weatherConditions: {
          temp: Math.floor(15 + ((seed + i) % 20)), // 15-35°C
          humidity: Math.floor(40 + ((seed + i) % 40)), // 40-80%
          pressure: Math.floor(995 + ((seed + i) % 25)) // 995-1020 hPa
        }
      });
    }
  }
  
  return episodes.reverse(); // Most recent first
};

export const generatePersonalizedStats = (userId?: string) => {
  const seed = userId ? userId.split('').reduce((a, b) => a + b.charCodeAt(0), 0) : Math.random() * 1000;
  
  return {
    currentRiskLevel: Math.floor(60 + (seed % 30)), // 60-90%
    totalEpisodes: Math.floor(35 + (seed % 25)), // 35-60 episodes
    avgDuration: (2.5 + (seed % 20) / 10).toFixed(1), // 2.5-4.5 hours
    weatherRelated: Math.floor(60 + (seed % 25)), // 60-85%
    monthlyTrend: (seed % 2 === 0 ? 1 : -1) * Math.floor(5 + (seed % 15)), // -20% to +20%
    aiConfidence: Math.floor(85 + (seed % 10)), // 85-95%
    weeklyTrend: (2.0 + (seed % 15) / 10).toFixed(1), // 2.0-3.5
    episodesThisMonth: Math.floor(6 + (seed % 8)), // 6-14 episodes
    predictionAccuracy: Math.floor(88 + (seed % 8)) // 88-96%
  };
};