// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnxdnbttrgodpyyqoaqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpueGRuYnR0cmdvZHB5eXFvYXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMzAwNTUsImV4cCI6MjA2ODgwNjA1NX0.Zj8MHtXbHSIVCdD9XFp6k4k14YHu5uqFjm8_8BKkwsY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});